# Generated by Django 2.0.2 on 2018-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('liandate', models.CharField(max_length=50)),
                ('anno', models.CharField(max_length=20)),
                ('executegov', models.CharField(max_length=10)),
                ('baodi', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('partycardnum', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'a02',
            },
        ),
    ]
